name: Check for dead repositories
on:
  push:
  pull_request:
  schedule:
    - cron: '30 5,17 * * *'
jobs:
  check-dead-repos:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          set-safe-directory: false
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y fish python3
      - name: Check dead repositories
        id: check
        run: fish .github/workflows/check-dead-repos.fish
